project_id = "nrvdpphlnxnpbdvqmqvm"

[functions.verify-otp]
verify_jwt = false

[functions.validate-action]
verify_jwt = false

[functions.tatum-generate-address]
verify_jwt = false

[functions.tatum-webhook]
verify_jwt = false

[functions.tatum-send-usdt]
verify_jwt = false